services:
  lernplan-reminder-bot-v2:
    build: .
    container_name: lernplan-reminder-bot-v2
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./data:/app/data
      - ./userconfig:/app/userconfig
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: ["CMD", "python", "src/healthcheck.py"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 15s
